model:
  target: fna_sra.t5_sra.FlanT5SLT
  params:
    lr: 6.0e-4
    monitor: val/cer
    model_name: google/flan-t5-xl
    cache_dir: /home/uic/project/huggingface_cache
    input_size: 1024
    inter_hidden: 768
    beam_size: 2
    max_frame_len: 512
    max_txt_len: 128
    frame_sample_rate: 1
    prompt: "Recognize the phoneme sequence of the given cued speech in {}."
    tuning_type: lora
    lora_r: 16
    lora_alpha: 32
    lora_dropout: 0.1
    fusion_mode: joint
    warm_up_steps: 0
    cross_modal_align: true
    combined_loss: true
    alpha: 1.0
    use_in_context: false
    num_in_context: 0
    eval_tokenizer: phoneme
    use_feature_norm: true
    use_triplet_loss: false
    triplet_margin: 1.0
    triplet_weight: 0.1
    use_global_feat: true
    global_cross_attn_heads: 8

lightning:
  callback:
    learning_rate_logger:
      target: pytorch_lightning.callbacks.LearningRateMonitor
      params:
        logging_interval: step
  trainer:
    accumulate_grad_batches: 4
    accelerator: gpu
    devices: 1
    max_epochs: 500
    gradient_clip_val: 1.0
    check_val_every_n_epoch: 2
    precision: bf16

data:
  target: dataset.datamodule.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 8
    train:
      target: dataset.mccsd.MCCSD
      params:
        anno_root:        ./preprocess/MCCSD_6H
        hand_feat_root:   /home/uic/fengling/mccsd/mccsd_datasets/Hand_Features/clip-vit-large-patch14_hand_feat_mccsd
        lip_feat_root:    /home/uic/fengling/mccsd/mccsd_datasets/Lip_Features/clip-vit-large-patch14_lip_feat_mccsd
        global_feat_root: null
        mode:             train
        spatial:          true
        spatiotemporal:   true
        target:           phoneme
    validation:
      target: dataset.mccsd.MCCSD
      params:
        anno_root:        ./preprocess/MCCSD_6H
        hand_feat_root:   /home/uic/fengling/mccsd/mccsd_datasets/Hand_Features/clip-vit-large-patch14_hand_feat_mccsd
        lip_feat_root:    /home/uic/fengling/mccsd/mccsd_datasets/Lip_Features/clip-vit-large-patch14_lip_feat_mccsd
        global_feat_root: null
        mode:             test
        spatial:          true
        spatiotemporal:   true
        target:           phoneme
    test:
      target: dataset.mccsd.MCCSD
      params:
        anno_root:        ./preprocess/MCCSD_6H
        hand_feat_root:   /home/uic/fengling/mccsd/mccsd_datasets/Hand_Features/clip-vit-large-patch14_hand_feat_mccsd
        lip_feat_root:    /home/uic/fengling/mccsd/mccsd_datasets/Lip_Features/clip-vit-large-patch14_lip_feat_mccsd
        global_feat_root: null
        mode:             test
        spatial:          true
        spatiotemporal:   true
        target:           phoneme
